{
  "name": "babel-plugin-async-function-try-catch",
  "version": "0.0.3",
  "description": "add try catch code blocks to async functions",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/zhijiang3/babel-plugin-async-function-try-catch.git"
  },
  "main": "lib/index.js",
  "keywords": [
    "babel-plugin"
  ],
  "author": {
    "name": "zhijiang3",
    "email": "zhijiang34@gmail.com"
  },
  "scripts": {
    "publish": "npm run build && npm publish",
    "lint": "prettier ./src/**/*.js --write",
    "test": "jest",
    "build": "babel src --out-dir lib"
  },
  "peerDependencies": {
    "@babel/core": "^7.0.0-0"
  },
  "devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.8.4",
    "@babel/preset-env": "^7.8.4",
    "@types/jest": "^25.1.3",
    "babel-jest": "^25.1.0",
    "babel-plugin-tester": "^8.0.1",
    "chalk": "^3.0.0",
    "glob": "^7.1.6",
    "husky": "^4.2.3",
    "jest": "^25.1.0",
    "lint-staged": "^10.0.7",
    "prettier": "^1.19.1"
  },
  "husky": {
    "hooks": {
      "pre-commit": "link-staged"
    }
  },
  "lint-staged": {
    "*.{js}": [
      "prettier --write",
      "git add"
    ]
  }
}
